version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "8081:80"     # alterei para evitar conflito
    volumes:
      - ./:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fightgym
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"   # evite conflito com MySQL local
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: {}   # <— precisa estar aqui, mesmo vazio
